 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/units", type: :request do
  # Unit. As you add validations to Unit, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Unit.create! valid_attributes
      get units_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      unit = Unit.create! valid_attributes
      get unit_url(unit)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_unit_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      unit = Unit.create! valid_attributes
      get edit_unit_url(unit)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Unit" do
        expect {
          post units_url, params: { unit: valid_attributes }
        }.to change(Unit, :count).by(1)
      end

      it "redirects to the created unit" do
        post units_url, params: { unit: valid_attributes }
        expect(response).to redirect_to(unit_url(Unit.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Unit" do
        expect {
          post units_url, params: { unit: invalid_attributes }
        }.to change(Unit, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post units_url, params: { unit: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested unit" do
        unit = Unit.create! valid_attributes
        patch unit_url(unit), params: { unit: new_attributes }
        unit.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the unit" do
        unit = Unit.create! valid_attributes
        patch unit_url(unit), params: { unit: new_attributes }
        unit.reload
        expect(response).to redirect_to(unit_url(unit))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        unit = Unit.create! valid_attributes
        patch unit_url(unit), params: { unit: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested unit" do
      unit = Unit.create! valid_attributes
      expect {
        delete unit_url(unit)
      }.to change(Unit, :count).by(-1)
    end

    it "redirects to the units list" do
      unit = Unit.create! valid_attributes
      delete unit_url(unit)
      expect(response).to redirect_to(units_url)
    end
  end
end
